web:
  api_host: 0.0.0.0:5000
  debug_host: 0.0.0.0:6060
  read_timeout: 5
  write_timeout: 5
  shutdown_timeout: 5
zipkin:
  local_endpoint: 0.0.0.0:3000
  reporter_uri: http://zipkin:9411/api/v2/spans
  service_name: gateway
  probability: 0.05
server:
  api_host: 0.0.0.0:7000
  read_timeout: 5
  write_timeout: 5
  shutdown_timeout: 5
